dlsuresumegenerator/urls.py
from django.conf.urls import url
from django.contrib import admin

import resumegeneratormain.views as views


urlpatterns = [
	url(r'^google_sign_in/$', views.google_sign_in, name='google_sign_in'),
	url(r'^$', views.index, name='index'),
	url(r'^login/$', views.login_view, name='login'),
    url(r'^form/$', views.form, name='form'),
	url(r'^register/$', views.register, name='register'),
	url(r'^generate/$', views.generate, name='generate'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^header/', views.header, name='header'),

]

resumegeneratormain/models.py
from django.db import models
from django.contrib.auth.models import User
import reversion


class Achievement(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class Address(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	address_line_one = models.TextField()
	address_line_two = models.TextField()

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class CellphoneNumber(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	number = models.CharField(max_length=20)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class ExtraCurricular(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	organization = models.CharField(max_length=45)
	position = models.CharField(max_length=45)
	work_done = models.TextField()
	year_start = models.DateField(max_length=4)
	year_finish = models.DateField(max_length=4)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class Education(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	school = models.CharField(max_length=45)
	education_attained = models.CharField(max_length=45)
	year_start = models.DateField(max_length=4)
	year_finish= models.DateField(max_length=4)
	month_attained = models.DateField(max_length=3)
	year_attained = models.DateField(max_length=4)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class EducationAward(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
	school = models.ForeignKey(Education, on_delete=models.CASCADE, null=True)
	award_description = models.CharField(max_length=45, blank=True, null=True)
	award_date = models.DateField(max_length=4, blank=True, null=True)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class ResearchPaper(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	month = models.CharField(max_length=3)
	year = models.CharField(max_length=4)
	title = models.CharField(max_length=70)
	summary = models.TextField()

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class SeminarAttended(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	month = models.CharField(max_length=3)
	year = models.CharField(max_length=4)
	title = models.CharField(max_length=45)
	seminar_head = models.CharField(max_length=45)
	venue = models.CharField(max_length=45)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class SeminarConducted(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	month = models.CharField(max_length=3)
	year = models.CharField(max_length=4)
	position = models.CharField(max_length=45)
	title = models.CharField(max_length=45)
	seminar_head = models.CharField(max_length=45)
	venue = models.CharField(max_length=45)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class TelephoneNumber(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	number = models.CharField(max_length=20)

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class UserProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	first_name = models.CharField(max_length=45)
	middle_initial = models.CharField(max_length=45)
	last_name = models.CharField(max_length=45)
	email = models.CharField(max_length=45)
	objective = models.TextField(blank=True, null=True)
	background = models.TextField()

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)


class WorkExperience(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	month_start = models.CharField(max_length=3)
	#year_start = models.CharField(max_length=4)
	month_finish= models.CharField(max_length=3)
	year_finish= models.CharField(max_length=4)
	position = models.CharField(max_length=45)
	company = models.CharField(max_length=45)
	workdone = models.TextField()

	def __str__(self):
		return 'User: {} {}'.format(self.user.last_name, self.user.first_name)

resumegeneratormain/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.template import loader

import numpy as np
import sys

#import shit for pylatex
import os
from pylatex import Document, Tabu, LineBreak, Command, StandAloneGraphic,MultiRow,Figure
from pylatex.utils import bold, NoEscape

from django.http import HttpResponse, HttpResponseNotFound, FileResponse

from resumegeneratormain.models import *
from reversion import views
from latexgenerate.generatetest import generatePDF


def google_sign_in(request):
	return render(request, "google_sign_in.html")

def index(request):
	return render(request, "test.html")

def form(request):
	return render(request, "RGhomepage.html")

def register(request):
	return render(request, "SignUp.html")

#def profile(request):
#	return render(request, "Profile.html")

def profile(request):
    	return render(request, 'profile.html')

def header(request):
    	return render(request, 'header.html')

def generate(request):
	geometry_options = {
	    "margin" : "1in",
	    "textwidth" : "2in",
	    "textheight" : "2in",
	    "headheight" : "0pt",
	    "headsep" : "0pt",
	    "footskip" : "0pt"
	}

	doc = Document(geometry_options=geometry_options)
	doc.preamble.append(Command("usepackage","times"))
	doc.preamble.append(Command("usepackage","graphicx"))
	doc.documentclass = Command('documentclass',options=['11pt'],arguments=['article'])	
	#Personal information header
	with doc.create(Tabu("X[l]  X[l]  X[r] ")) as table: #Personal Information
	    table.add_row(bold("Juan De la Cruz"),"",MultiRow(5,data=Command('includegraphics','juandelacruz','width=100px,height=80px'))) #Name and Photo(photo must be in same folder)
	    table.add_row("1234 Taal Street, Singalong, Malate, Manila 1004",
	    "23 Maison Road, Malinta, Valenzuela City 1440",
	    "") #Address1 & Address2 
	    table.add_row("(02) 123-4567; 123-4567", 
	    "(02) 123-4567",
	    "") #Landline number
	    table.add_row("+63917891234","","") #mobile number
	    table.add_row("juancruz@yahoo.com","","") #email
	    table.add_empty_row()	
	with doc.create(Tabu("X[l] X[3l]")) as table: #Objective
	    table.add_row(bold("OBJECTIVE"),"") 
	    table.add_empty_row()
	    table.add_row("","To join an organization where I can use my skills in personnel administration and attain a high level of performance in personnel recruitment and training.") #Objective
	    table.add_empty_row()	
	with doc.create(Tabu("X[l] X[3l]")) as table: #Education
	    table.add_row(bold("EDUCATION"),"")
	    table.add_empty_row()
	    table.add_row("YEAR","UNIVERSITY") #Year and Univesity attended
	    table.add_row("","Degree and academic related awards") #Degree & Awards
	    table.add_empty_row()
	    table.add_row("YEAR","HIGHSCHOOL") #Year and Highschool attended
	    table.add_row("","academic related awards") #Awards
	    table.add_empty_row() 

	with doc.create(Tabu("X[l] X[3l]")) as table: #Work
	    table.add_row(bold("WORK EXPERIENCE"),"")
	    table.add_empty_row()
	    table.add_row("Month Year - Month Year",
	    "PRACTICUM TRAINEE, FEDERAL EXPRESS") #Position & Company
	    table.add_row("","Assited the Research and Development Superviser in gathering data............") #Job description
	    table.add_empty_row()
	    table.add_row("Month Year - Month Year",
	    "ACCOUNT EXECUTIVE, CITIBANK") #Position & Company
	    table.add_row("","Handled the accounts of new customers and advised them on their financial endeavors.") #Job description
	    table.add_empty_row()	
	with doc.create(Tabu("X[l] X[3l]")) as table: #Co-Curricular Activities
	    table.add_row(bold("CO-CURRICULAR ACTIVITIES"),"")
	    table.add_empty_row()
	    table.add_row("YEAR-YEAR","RESEARCH AND DEVELOPMENT HEAD, DLSU-COUNCIL OF STUDENT ORGANIZTIONS(CSO)") #Position & Company
	    table.add_row("","Initiated the following projects: CSO budget defense proposal.........") #description
	    table.add_empty_row()

	with doc.create(Tabu("X[l] X[3l]")) as table: #Seminars Attended
	    table.add_row(bold("SEMINARS ATTENDED"),"")
	    table.add_empty_row() 
	    table.add_row("MONTH YEAR","RELATIONSHIPS SEMINAR") #Month and Year of Seminar and Title of Seminar
	    table.add_row("","Student Development Office, De La Salle University") #Host of Seminar and Venue
	    table.add_empty_row()	
	with doc.create(Tabu("X[l] X[3l]")) as table: #Seminars Conducted
	    table.add_row(bold("SEMINARS CONDUCTED"),"")
	    table.add_empty_row()
	    table.add_row("MONTH YEAR", "FACILITATOR, RELATIONSHIPS SEMINAR") #Month & Year of seminar and Role & Title
	    table.add_row("","Student Development Office, De La Salle University") #Host of seminar and venue
	    table.add_empty_row()

	with doc.create(Tabu("X[l] X[3l]")) as table: #Research Papers
	    table.add_row(bold("RESEARCH PAPERS PREPARED"),"")
	    table.add_empty_row()
	    table.add_row("MONTH YEAR","AN ORDERED PROBIT MODEL OF APPLICATIONS TO DLSU'S BUSINESS........") #Month & Year and Title of paper
	    table.add_row("","Estimated a utility function that discusses the probabilities of highschool graduates......") #Description of paper
	    table.add_empty_row()

	with doc.create(Tabu("X[l] X[3l]")) as table: #Personal background
	    table.add_row(bold("PERSONAL BACKGROUND"),"")
	    table.add_empty_row()
	    table.add_row("","Fluent in English and Filipino. Knowledgeable in MS programs........") 
	    table.add_empty_row()

	with doc.create(Tabu("X[l] X[3l]")) as table: #References
	    table.add_row(bold("REFERENCES"),"") 
	    table.add_empty_row()
	    table.add_row("", "PAMELA S. SANTOS") #name
	    table.add_row("","PSYCHOLOGY PROFESSOR") #position
	    table.add_row("","987-6543; +63917876543;pamela.santos@dlsu.edu.ph") #contact details
	    table.add_row("","2401 Taft Ave, Malate, Manila, 1004 Metro Manila") #address
	    table.add_empty_row()

	doc.generate_pdf("DLSUResume", clean_tex=False)	
	return FileResponse(open('DLSUResume.pdf','rb'), content_type='application/pdf')


## TODO: CATCH THE EXCEPTION WHEN AN ACCOUNT WITH THE SAME CREDENTIALS IS MADE
#def register_account(request):
#	if request.method =="POST":
#		username = request.POST['username']
#		first_name = request.POST['first_name']
#		last_name = request.POST['last_name']
#		email = request.POST['email']
#		password = request.POST['password']	
#		user = User.objects.create_user(username = username, email = email, password = password)
#		user.first_name = first_name
#		user.last_name = last_name
#		user.save()
#	return redirect('index')


# TODO: Add a "user does not exist" alert #alert('user typed is incorrect') 
def login_view(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username = username, password = password)
		if user is not None:
			if user.is_active:
				login(request,user)
				return redirect('form')
			else:
				return HttpResponseNotFound('<h1>User is inactive. Please inform the administrator.')
		else:
			return HttpResponseNotFound('<h1>User does not exist')

	else:
		return render(request, "index")

def logout_view(request):
	logout(request)
	return redirect('index')

resumegeneratormain/templates/BlankResume.html
<html>
  <head>
		{% load staticfiles %}
		<!-- replace when moving to django -->
  	<!--<link href="{% static 'resumegeneratormain/css/blank-resume.css' %}" rel="stylesheet" type="text/css">-->
		<link href="../static/resumegeneratormain/css/blank-resume.css" rel="stylesheet" type="text/css">

  </head>
  <body>
		<!-- Photo disabled until a better implementation is found -->
		<!--<img src='DSC_6641.jpg' id='photo'>-->

		<div class='header'>
 			<p style='font-weight: bold;'>{{user.userprofile_set.first.first_name}} {{user.userprofile_set.first.middle_initial}}. {{user.userprofile_set.first.last_name}}</p>
			<p>
				{{user.address_set.first.address_line_one}} <br>
				{{user.address_set.first.address_line_two}} <br>
				{{user.telephonenumber_set.first.number}} <br>
				{{user.userprofile_set.first.email}} <br>
			</p>

		</div>


		<br>
		<br>

		<div class='objective'>
			<p id='section-header'>OBJECTIVE</p>
			<br>
			<p id='section-content-right'>
				{{user.userprofile_set.first.objective}}
			</p>

		</div>

		<br>
		<br>

		<div class='education'>
			<p id='section-header'>EDUCATION</p>
			<br>
			{% for education in user.education_set.all %}
      	<p id='section-content-left'>
        	{{education.year_start}} - {{education.year_finish}}
        </p>

        <p id='section-content-right'>
            {{education.school}}
            <br>
            {{education.education_attained}}, {{education.month_attained}} {{education.year_attained}}.

            {% for educationaward in user.educationaward_set.all %}
                {{educationaward.award_description}}, {{educationaward.award_date}}.
            {% endfor %}
        </p>
        <br>
      {% endfor %}

		</div>

		<br>
		<br>

		<div class='workexperience'>
			<p id="section-header">WORK EXPERIENCE</p>
			<br>
			{% for workexp in user.workexperience_set.all %}
      	<p id='section-content-left'>
        	{{workexp.month_start}} - {{workexp.month_finish}} {{workexp.year_finish}}
        </p>
        <p id='section-content-right'>
          {{workexp.position}}, {{workexp.company}}.
					<br>
					{{workexp.workdone}}
        </p>
        <br>
    	{% endfor %}

		</div>

		<br>
		<br>

		<div class='cocurricular'>
			<p id='section-header'>CO-CURRICULAR ACTIVITIES</p>
			<br>
			{% for curricular in user.extracurricular_set.all %}
      	<p id='section-content-left'>
        	{{curricular.year_start}} - {{curricular.year_finish}}
        </p>
        <p id='section-content-right'>
          <b>{{curricular.position}}, {{curricular.organization}}</b>
          <br>
          {{curricular.work_done}}
        </p>
          <br>
      {% endfor %}


		</div>

		<br>
		<br>

		<div class='seminarsattended'>
			<p id='section-header'>SEMINARS ATTENDED</p>
			<br>

			{% for seminarattend in user.seminarattended_set.all %}
      	<p id='section-content-left'>
          {{seminarattend.month}} {{seminarattend.year}}
        </p>
        <p id='section-content-right'>
          <b>{{seminarattend.title}}</b>
          <br>
          {{seminarattend.seminar_head}}, {{seminarattend.venue}}.
        </p>
        <br>
      {% endfor %}
		</div>

		<br>
		<br>

		<div class='seminarsconducted'>
			<p id="section-header">SEMINARS CONDUCTED</p>
			<br>
      {% for seminarconduct in user.seminarconducted_set.all %}
      	<p id='section-content-left'>
					{{seminarconduct.month}} {{seminarconduct.year}}
				</p>
				<p id='section-content-right'>
					{{seminarconduct.position}}, {{seminarconduct.title}}
          <br>
          {{seminarconduct.seminar_head}}, {{seminarconduct.venue}}.
        </p>
        <br>
			{% endfor %}
		</div>

		<br>
		<br>

		<div class='researchprepared'>
			<p id="section-header">RESEARCH PAPERS PREPARED</p>
			<br>
			{% for researchpaper in user.researchpaper_set.all %}
      	<p id='section-content-left'>
				{{researchpaper.month}} {{researchpaper.year}}
        </p>
				<p id='section-content-right'>
        	<b>{{researchpaper.title}}</b>
          <br>
          {{researchpaper.summary}}
				</p>
        <br>
      {% endfor %}
		</div>

		<br>
		<br>

		<div class='personalbackground'>
      <p id='section-header'>PERSONAL BACKGROUND</p>
			<br>
			<p id='section-content-right'>
				{{user.userprofile_set.first.background}}
			</p>

		</div>

		<br>
		<br>

		<div class='references'>
			<p id='section-header'>REFERENCES</p>
			<br>
			<p id='section-content-right'>
				Available upon request.
			</p>

		</div>

		<br>
		<br>
	</body>


</html>

resumegeneratormain/templates/SignUp.html
    <html>
    <head>
			{% load staticfiles %}
        <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static "resumegeneratormain/css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "resumegeneratormain/css/style.css" %}" rel="stylesheet">

        <script src="{% static "resumegeneratormain/js/jquery.min.js" %}"></script>
        <script src="{% static "resumegeneratormain/js/bootstrap.min.js" %}"></script>
        <script src="{% static "resumegeneratormain/js/classie.js" %}"></script>

        <script src="//use.edgefonts.net/montserrat.js"></script>
        <script src="//use.edgefonts.net/anonymous-pro:n4,i4,n7,i7.js"></script>

    </head>

    <body>

        <div class = "icon">
            <img src = "{% static "resumegeneratormain/images/icon.png" %}"  width = "77px" height= "107px">
            <br>
            <h1>Account Sign Up</h1>
            <br>
        </div>

				<!-- TODO: For Janz, add mo yung 'name=' for the user reg -->
        <form method="POST" action="/register_account/">
          {% csrf_token %}
        <div class = "logIn">
            <div class="row">
              <div class="col-md-4"></div>
              <div class="input-group col-md-4">
                  <span class="input-group-addon" id="basic-addon1">Username: </span>
                  <input type="text" class="form-control" id = "user" aria-describedby="basic-addon1" name="username">
              </div>
              <br>
              <div class="col-md-4"></div>
              <div class="input-group col-md-4">
                  <span class="input-group-addon" id="basic-addon1">First Name and Middle Initial: </span>
                  <input type="text" class="form-control" id = "user" aria-describedby="basic-addon1" name="first_name">
              </div>
              <br>
              <div class="col-md-4"></div>
              <div class="input-group col-md-4">
                  <span class="input-group-addon" id="basic-addon1">Last Name: </span>
                  <input type="text" class="form-control" id = "user" aria-describedby="basic-addon1" name="last_name">
              </div>
              <br>
              <div class="col-md-4"></div>
              <div class="input-group col-md-4">
                  <span class="input-group-addon" id="basic-addon1">E-mail: </span>
                  <input type="text" class="form-control" id = "user" aria-describedby="basic-addon1" name="email">
              </div>
              <div class="col-md-4"></div>
              <br>
              <div class="row">
                <div class="col-md-4"></div>
                <div class="input-group col-md-4">
                    <span class="input-group-addon" id="basic-addon1">Password </span>
                    <input type="password" class="form-control" id = "pass" aria-describedby="basic-addon1" name="password">
                </div>
                <br>
                <br>
                <div class="col-md-4"></div>
                <div class="col-md-1">
                    <a href = "{% url "index" %}" id = "login" class="btn btn-1 btn-1a">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>Cancel</a>
                </div>
                <div class="">
                  <input id = "login" type="submit" value="Register Account">
                </div>
              </div>
            </div>
        </div>
        </form>


    </body>
</html>

resumegeneratormain/templates/google_sign_in.html
<html lang="en">
  <head>
    <meta name="google-signin-scope" content="profile email">
    <meta name="google-signin-client_id" content="826392665545-avram6uos8j0bda31pn2tvj06pgleukt.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
  </head>
  <body>
    <div class="g-signin2" data-onsuccess="onSignIn" data-theme="dark"></div>
    <script>
      function onSignIn(googleUser) {
        // Useful data for your client-side scripts:
        var profile = googleUser.getBasicProfile();
        console.log("ID: " + profile.getId()); // Don't send this directly to your server!
        console.log('Full Name: ' + profile.getName());
        console.log('Given Name: ' + profile.getGivenName());
        console.log('Family Name: ' + profile.getFamilyName());
        console.log("Image URL: " + profile.getImageUrl());
        console.log("Email: " + profile.getEmail());

        // The ID token you need to pass to your backend:
        var id_token = googleUser.getAuthResponse().id_token;
        console.log("ID Token: " + id_token);
      };
    </script>
  </body>
</html>

resumegeneratormain/templates/header.html
<!--
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/custom.css"> 
        <link rel="stylesheet" type="text/css" href="css/skeleton.css"> 
        
        <script>
            function myFunction() 
            {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
    </head>
        
    <body>
       
        <div class="container">
            <div class="row topnav" id="myTopnav">
                <a class="two columns header-margin" style="text-align: left;">DASHBOARD</a>
                <a class="two columns text-center header-margin">CATEGORIES</a>
                <div class="four columns center">
                    <img src="images/black%20ego.png" class="header-img-margin">
                </div>
                <a class="two columns text-center header-margin">MY RESUMES</a>
                <a class="two columns text-center header-margin" style="text-align: right;">PROFILE</a>
                <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>
            </div>
        </div>
    </body>
    
</html>
-->
<html>
    <head>
        {% load staticfiles %}
        <link href = "{% static "resumegeneratormain/css/skeleton.css" %}" rel="stylesheet">
        <link href = "{% static "resumegeneratormain/css/custom.css" %}" rel="stylesheet">
        {% block other_static_files %}
        {% endblock %}
    
        <script>
            function myFunction() 
            {
                var x = document.getElementById("myTopnav");
                if (x.className === "topnav") {
                    x.className += " responsive";
                } else {
                    x.className = "topnav";
                }
            }
        </script>
        
    </head>
        
    <body>
        <div class="container snip1135">
            <div class="row">
                <li class="current"><a href="#" data-hover="DASHBOARD">DASHBOARD</a></li>
                <li><a href="#" data-hover="CATEGORIES">CATEGORIES</a></li>
                <li class="center">
                    <img src="{% static "resumegeneratormain/images/blackego.png" %}" class="header-img-margin">
                </li>
                <li class="center"><a href="#" data-hover="MY RESUMES">MY RESUMES</a></li>
                <li class="center"><a href="#" data-hover="PROFILE">PROFILE</a></li>
            </div>
        </div>
        {% block content %}
        {% endblock %}

    </body>
    
</html>

resumegeneratormain/templates/index.html
<<<<<<< HEAD

<html>
    <head>
            {% load staticfiles %}
        <link href = "{% static "resumegeneratormain/css/skeleton.css" %}" rel="stylesheet">
        <link href = "{% static "resumegeneratormain/css/custom.css" %}" rel="stylesheet">
        <link href = "{% static "resumegeneratormain/css/animate.css" %}" rel="stylesheet">

        <style>
            body { 
                background-color: #79A280;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="six columns animated slideInLeft">
                    <img src="{% static "resumegeneratormain/images/whiteego.png" %}" style="height: 130px; width: auto; margin-top: 180px; margin-bottom: 30px;">
                    <hr>
                    <p class="white">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
                <div class="six columns animated slideInDown">  
                    <div class="flex-container whitebox">
                        <div class="margin-whitebox">
                            <h6 class="bold marginh6">Email</h6>
                            <div id="input_container">
                                <img src="{% static "resumegeneratormain/images/at.png" %}" id="input_img">
                                <input id="at-icon" class="text-line" style="width: inherit;"type="text" placeholder="john_appleseed@apple.com"/>
                            </div>
                            <h6 class="bold marginh6" style="margin-top: 5px;">Password</h6>
                            <div id="input_container">
                                <img src="{% static "resumegeneratormain/images/lock.png" %}" id="input_img">
                                <input id="at-icon" class="text-line" style="width: inherit;"type="password" placeholder="•••••••••"/>
                            </div>

                            <div class="custom-container wide" style="margin-top: 2rem;">
                                    <div class="six columns">
                                        <span style="float: left;">
                                            <input type="checkbox" name="checkbox" id="checkbox_id" value="value">
                                            <label for="checkbox_id" class="small">Remember Me</label>
                                        </span>
                                    </div>
                                    <div class="six columns">
                                        <button style="float: right;">Sign In</button>
                                    </div>
                            </div>
                            <fieldset class="title">
                                <legend>or</legend>
                            </fieldset>
                            <div class="custom-container">
                                <input type="image" src="{% static "resumegeneratormain/images/google-signin.png" %}" alt="Submit" width="50%" height="auto" class="img-border">
                            </div>
                            
                        </div>
                    </div>
                    <div class="flex-container greenbox">
                        <div style="margin-top:8px;">
                            <h6 class="white center medium">Don't have an account? <a class="white bold">Sign up here.</a></h6>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </body>
</html>

resumegeneratormain/templates/test.html
<html>
  <head>
    {% load staticfiles %}
      <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link href="{% static "resumegeneratormain/css/bootstrap.min.css" %}" rel="stylesheet">
      <link href="{% static "resumegeneratormain/css/style.css" %}" rel="stylesheet">
      <script src="//use.edgefonts.net/montserrat.js"></script>
  </head>
  <body>
      <div class = "test-main">
          <div class="row">
            <div class="row">
                <div class = "test">
                    <h5>Not yet registered? <a href="{% url "generate" %}"><u>Generate PDF</u></a></h5>
                </div>
            </div>
          </div>
      </div>
  
  <script src="{% static "resumegeneratormain/js/jquery.min.js" %}"></script>
  <script src="{% static "resumegeneratormain/js/bootstrap.min.js" %}"></script>
  
  </body>
  </html>
  